export enum TagTypes {
  EMPLOYEE = "Employees",
  DASHBOARD_STATS = "Dashboard_Stats",
  TRANSFER = "Transfers",
  AUTH = "Auth",
  INVENTORY_UNITS = "Inventory_Units",
  INVENTORY_CATEGORIES = "Inventory_Categories",
  INVENTORY_ITEMS = "Inventory_Items",
  STOCK_MOVEMENTS = "Stock_Movements",
  SUPPLIERS = "Suppliers",
  MEDIA = "Media",
  GALLERY = "Gallery",
  ADMIN = "Admin",
  ACTIVITY_RECORDS = "Activity_Records",
  NOTIFICATIONS = "Notifications",
}
