services:
    mongo:
        container_name: mongo
        hostname: mongo
        image: mongodb/mongodb-atlas-local:8
        volumes:
            - mongo-data:/data/db
            - mongo-config:/data/configdb
        ports:
            - "27018:27017"

volumes:
    mongo-data:
    mongo-config:
