import express from "express";
const router = express.Router();

import authRouter from "../modules/auth/auth.router";
import banksRouter from "../modules/banks/banks.router";
import employeesRouter from "../modules/employees/employees.router";
import dashboardRouter from "../modules/dashboard/dashboard.router";
import transfersRouter from "../modules/transfers/transfers.router";
import transactionsRouter from "../modules/transactions/transactions.router";
import webhooksRouter from "../modules/webhooks/webhooks.router";
import inventoryUnitsRouter from "../modules/inventory-units/inventory-units.router";
import inventoryCategoriesRouter from "../modules/inventory-categories/inventory-categories.router";
import inventoryItemsRouter from "../modules/inventory-items/inventory-items.router";
import stockMovementRouter from "../modules/stock-movement/stock-movement.router";
import suppliersRouter from "../modules/suppliers/suppliers.router";
import mediaRouter from "../modules/media/media.router";
import galleryRouter from "../modules/gallery/gallery.router";
import adminsRouter from "../modules/admins/admins.router";
import activityTrackingRouter from "../modules/activity-tracking/activity-tracking.router";
import notificationsRouter from "../modules/notifications/notifications.router";

router.use(authRouter);
router.use(banksRouter);
router.use(employeesRouter);
router.use(dashboardRouter);
router.use(transfersRouter);
router.use(transactionsRouter);
router.use(webhooksRouter);
router.use(inventoryUnitsRouter);
router.use(inventoryCategoriesRouter);
router.use(inventoryItemsRouter);
router.use(stockMovementRouter);
router.use(suppliersRouter);
router.use(mediaRouter);
router.use(galleryRouter);
router.use(adminsRouter);
router.use(activityTrackingRouter);
router.use(notificationsRouter);

export default router;
